version: '3'
services:
  db:
    image: mysql:5.7
    container_name: crudmysql_database_container
    ports:
      - '3307:3306'
    volumes:
      - "./database:/data/application"
    command: --init-file /data/application/db.sql
    networks:
      - crud_net
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=aaa
      - MYSQL_ROOT_PASSWORD=aaa

  web:
    build: ./
    container_name: crudmysql_web_container
    ports:
      - "3000:3000"
    networks:
      - crud_net
    command: sh -c '/usr/src/app/wait-for-it.sh -t 0 db:3306 -- npm run devstart'
    depends_on:
      - db

networks:
  crud_net:
